website/auth.py
# ----------<AUTH.PY>------------------------------------------------------------------------------------#
#
# ----------<IMPORTS>------------------------------------------------------------------------------------#
#
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, Admin
from . import db
from flask_login import login_user, login_required, logout_user, current_user
#
# ----------<BUEPRINTS>------------------------------------------------------------------------------------#
#
auth = Blueprint("auth", __name__)  # for authorizing user
#
authAdmin = Blueprint("authAdmin", __name__)  # for authorizing Admin access
#
# ----------<LOGIN/LOGOUT>------------------------------------------------------------------------------------#
#
#
# LOGIN
@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                if user.enabled_user == True:
                    return redirect(url_for("views.home"))
                else:
                    return (
                        "<h1>Account Disabled!</h1><h3>*See- violation: policies. </h3>"
                    )
            else:
                flash("WTF!", category="error")
                flash("Incorrect password, use KeePass!", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login.html", user=current_user)
#
#
# LOGOUT
@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))
#
#
# ----------<SIGN-UP>------------------------------------------------------------------------------------#
# SIGN_UP
@auth.route("/sign-up", methods=["GET", "POST"])
def sign_up():
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")
        backup_email = request.form.get("backup_email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be more than 4 characters!", category="error")
        elif email == backup_email:
            flash("backup email is the same as your main email!", category="warning")
        elif len(username) < 2:
            flash("Username must be more than 2 characters!", category="error")
        elif password1 != password2:
            flash("Passwords must match!", category="error")
        elif len(password1) < 7:
            flash("Password must be more than 7 characters!", category="error")
        else:
            new_user = User(
                email=email,
                backup_email=backup_email,
                username=username,
                password=generate_password_hash(password1),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Success!", category="success")
            flash("Account created!", category="success")
            
            return redirect(url_for("views.home"))

    return render_template("sign_up.html", user=current_user)
#
#
# ----------<ADMIN_ACCOUNT>------------------------------------------------------------------------------------#
#
#
# ADMIN_ACCOUNT_CREATE
@auth.route("sign_upadmin/", methods=["GET", "POST"])
def createAdmin():
    if request.method == "POST":
        email = request.form.get("email")
        backup_email = request.form.get("backup_email")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")

        user = Admin.query.filter_by(email=email).first()
        if user:
            flash("Email already exists.", category="error")
        elif len(email) < 4:
            flash("Email must be more than 4 characters!", category="error")
        elif email == backup_email:
            flash("backup email is the same as your main email!", category="warning")
        elif password1 != password2:
            flash("Passwords must match!", category="error")
        elif len(password1) < 7:
            flash("Password must be more than 7 characters!", category="error")
        else:
            new_user = Admin(
                email=email,
                backup_email=backup_email,
                password=generate_password_hash(password1),
            )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash("Success!", category="success")
            flash("Account created!", category="success")
            return redirect(url_for("views.dashboard_admin"))

    return render_template("sign_upadmin.html", user=current_user)
#
#
# ADMIN_LOGIN
@auth.route("login_admin/", methods=["GET", "POST"])
def loginAdmin():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")

        user = Admin.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in successfully!", category="success")
                login_user(user, remember=True)
                if user.enabled_user == True:
                    return redirect(url_for("views.dashboard_admin"))
                else:
                    return (
                        "<h1>Account Disabled!</h1><h3>*See- violation: policies. </h3>"
                    )
            else:
                flash("WTF!", category="error")
                flash("Incorrect password, use KeePass!", category="error")
        else:
            flash("Email does not exist.", category="error")

    return render_template("login_admin.html", user=current_user)
#
#
# ----------<END>------------------------------------------------------------------------------------#

website/templates/about.html
{% extends "base_auth.html" %}
{% block title %}About{% endblock %}
{% block content %}

  <body>
    <h1>Welcome to Our Finance Application</h1>
    <p>
        Where financial empowerment meets simplicity. Our application is designed to revolutionize the way you manage your finances, offering intuitive tools and features that empower users to take control of their financial journey. From seamless budget tracking to insightful analytics, we provide a comprehensive suite of tools to help you achieve your financial goals. Our Finance Application ensures a hassle-free and secure experience with a user-friendly interface and robust security measures. Whether you're tracking expenses, planning for the future, or gaining insights into your spending patterns, our application is your trusted companion on the path to financial success. Join us on this journey toward financial well-being, where every transaction has the power of saving better.
    </p>

    <h2>Meet Our Team</h2>
    <p>
        Our team is comprised of passionate individuals with a shared vision for financial empowerment. We are committed to providing a seamless and secure experience for our users, offering a comprehensive suite of tools to help you achieve your financial goals. Our team is dedicated to continuous innovation, ensuring that our application is equipped with the latest features and technology. We are committed to providing a positive and stress-free experience for our users, with a friendly and knowledgeable support team available to assist you every step of the way. We are here to help you take control of your financial journey, one transaction at a time.
    </p>
    <hr>
    <div class="team-member">
        <h3>Charles Drexler: CEO</h3>
        <p>
            Charles is the driving force behind our Finance Application, bringing a wealth of experience in the finance industry. With a vision for making financial management accessible to all, Charles has led our team in developing intuitive tools that redefine the way users engage with their finances. His commitment to innovation and financial empowerment sets the tone for our entire organization.
        </p>
    </div>

    <div class="team-member">
      <h3>Caleb Turner: Chief Technology Officer</h3>
      <p>
          As our CTO, Caleb is the technological mastermind responsible for the seamless functionality and security of our Finance Application. With a background in cutting-edge technology, Caleb ensures that our users have a reliable and secure platform to manage their financial data. His expertise in software development and commitment to staying ahead of industry trends drives the continuous improvement of our application.
      </p>
  </div>

  <div class="team-member">
      <h3>Donnie Bowles: Head of Customer Experience</h3>
      <p>
          Donnie is the friendly face behind our commitment to excellent customer service. As Head of Customer Experience, he ensures that our users have a positive and stress-free interaction with our Finance Application. Donnie's dedication to customer satisfaction and problem-solving skills make him an invaluable asset to our team.
      </p>
  </div>

  <div class="team-member">
      <h3>Maryam Aifa: Financial Analyst</h3>
      <p>
          Maryam is our analytical powerhouse, bringing a keen eye for financial trends and insights. As a Financial Analyst, she plays a crucial role in refining our application's analytics features. Maryam's expertise in data analysis and her passion for helping users make informed financial decisions contribute to the robust analytical capabilities of our Finance Application.
      </p>
  </div>

  <div class="team-member">
      <h3>Ater Ater: UX/UI Designer</h3>
      <p>
          Ater is the creative force responsible for the visually appealing and user-friendly design of our Finance Application. As a UX/UI Designer, Ater combines aesthetics with functionality to create an engaging and intuitive user experience. His innovative designs enhance the overall usability of our application, making financial management an enjoyable experience for our users.
      </p>
  </div>
    <!-- Other team members go here -->
  <nav>
    <hr>

    <h2 align="center">Contact Us</h2>
    <p align="center">Share your thoughts with us! This is a test about our app. We'd love to hear from you!</p>

    <form method="POST" class="container pie-card">
      <div class="form-group">
        <label for="comment">Comment</label>
        <input
          type="text"
          class="form-control"
          id="comment"
          name="comment"
          placeholder="Enter your comments here"
        />
      </div>

      <div class="form-group">
        <label for="email">Your Email</label>
        <input
          type="email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter your email address"
        />
      </div>

      <br />
      <button type="submit" class="btn btn-primary">Send</button>

      <hr>
    </form>
    <hr>
  </body>
{% endblock %}

website/templates/base_auth.html
<!DOCTYPE html>
<html>
  <head>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
      />
      <style>
        body {
          font-family: 'Open Sans', Arial, sans-serif;
          font-size: 16px;
          
          line-height: 1.6;
          color: #333;
          margin: 1px;
          background-color: #040720; /* Add a subtle background color */

        }
        .container {
          max-width: 1000px; /* Add a maximum width */
          margin: 0 auto; /* Center it */
          padding: 0 20px; /* Add some padding */
          backgroundColor: #040720;
        }
        label {
          color: #f8f9fa; /* Light text color */}
        
        .blue-black { 
          background-color: #040720; /* Darker background color and add a transition on hover */
          color: #f8f9fa; /* Grey text color */
          borderColor: #040720; /* Add a dark border */
          font-family: 'Open Sans', Arial, sans-serif;
          font-size: 16px;
          line-height: 1.6;
          color: #333;
          margin: 1px;
          background-color: #040720; /* Add a subtle background color */
        }

        
   
        input, form, .form-group, .form-control {
          font-size: 18px;
          padding: 10px;
          border: 1px solid #ddd;
          border-radius: 5px;
          margin-top: 5px;
          background-color: #333333; /* Darker background for inputs */
          color: #f8f9fa; /* Light text color */
          border-color: #444444; /* Dark border color */
          
        }
        .list-group-item, .list-group-item-action, .list-group-item-success:hover, .list-group-item-success:focus {
          font-size: 18px;
          padding: 10px;
          border: 1px solid #ddd;
          border-radius: 5px;
          margin-top: 5px;
          background-color: #333333; /* Darker background for inputs */
          color: #f8f9fa; /* Light text color */
          border-color: #444444; /* Dark border color */
          
       }
      font-size: 18px;
          padding: 10px;
          border: 1px solid #ddd;
          border-radius: 5px;
          margin-top: 5px;
          background-color: #333333; /* Darker background for inputs */
          color: #f8f9fa; /* Light text color */
          border-color: #444444; /* Dark border color */
          
 
      h4, h5, h6 {

          font-family: 'Pacifico', cursive; /* Use Pacifico for headings */
          
          color: #f8f9fa ; /* Heading color */
        }
      h1, h2 , h3 {
          font-family: 'Pacifico', cursive; /* Use Pacifico for headings */
          color: gold; /* Heading color */
        }
      
      p,a {
          margin-bottom: 15px;
          color: #f8f9fa; /* Light text color */;
        }
        .port-card {
          width: 100%;
          margin-bottom: 30px;
          padding: 20px; /* Add consistent padding */
          color: #f8f9fa; /* Light text color */;

          background-color: #333333; /* Add a dark background color to the card */
          border-radius: 8px; /* Add rounded corners */
          box-shadow: 0 0 10px rgba(0, 0, 0.1, 0.1); /* Add a subtle box shadow */
        }
        .pie-card {
          max-width: 40%;
          margin-bottom: 30px;
          padding: 20px; /* Add consistent padding */
          background-color: #040720 ; /* Add a dark background color to the card */
          border-radius: 8px; /* Add rounded corners */
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
        }
        .blue-card{
          margin-bottom: 30px;
          padding: 20px; /* Add consistent padding */
          background-color: #040720 ; /* Add a dark background color to the card */
          border-radius: 8px; /* Add rounded corners */
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
        }
      
        .team-member {
          margin-bottom: 30px;
          padding: 20px; /* Add consistent padding */
          background-color: #333333; /* Add a dark background color to the card */
          border-radius: 8px; /* Add rounded corners */
          box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Add a subtle box shadow */
        }
      
        .team-member h3 {
          color: #1E90FF; /* Subheading color */
        }
      
        .team-member img {
          max-width: 100%;
          border-radius: 50%;
          margin-bottom: 10px;
        }
      
        /* Adjust button styling */
        .btn-primary {
          background-color: gold;
          color: #333;
          border: 1;
          padding: 5px 10px;
          border-radius: 10px 10px;
          cursor: pointer;
        }
        .btn-group {
          background-color: #040720;
          color: #333;
          border: 2;
          padding: 5px 20px;
          border-radius: 10px;
          cursor: pointer;
        }
        "btn btn-secondary" {
          background-color: gold;
          color: #333;
          border: 1;
          padding: 5px 20px;
          border-radius: 10px;
          cursor: pointer;
        }
      
        h2 {
          text-align: center;
        }


      
      
        /* Add more styles as needed */
        </style>
      <title>{% block title %}BASE{% endblock %}</title>
    </head>
    <body>
      
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
        >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/home">
            <img src="{{ url_for('static', filename='images/Finance_logo.png') }}" alt="Your Logo" width="30" height="30" href="/home">
          </a>
          <hr>
          <a class="navbar-brand" href="/info">|  {{ current_user.username }}  | </a>
          <a class="nav-item nav-link" id="DashBoard" href="/home"
          >Finance</a >
          <a class="nav-item nav-link" id="support" href="/public/calculator"
          >Calculator</a>
          <a class="nav-item nav-link" id="about" href="/public/about">About</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <div  class="settings wrapper svelte-14p79g3">
            
          </svg></button> <style data-svelte-h="svelte-1adm154">#settings-button {
                display: "/settings";
              }</style>
             <a  id="settings-button-ns" class="btn btn--icon btn--sm svelte-14p79g3 nav-justified nav-item nav-link" href="/settings" aria-label="Settings">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="none" class="icon"  align="right" viewBox="1 1 26 26">
                
                <path fill="currentColor" fill-rule="evenodd" d="M13 18.143c-.062 0-.125 0-.188-.003l-.857 1.305a.927.927 0 0 1-1.027.384A7.5 
              7.5 0 0 1 7.8 18.04a.921.921 0 0 1-.18-1.084l.713-1.39a5.435 5.435 0 0 1-.183-.313l-1.574-.084a.922.922 0 0 1-.85-.69 7.335 7.335 0 0 
              1-.226-1.797c0-.605.077-1.206.226-1.797.1-.393.448-.67.847-.69l1.577-.083c.057-.106.118-.21.183-.314l-.712-1.39a.922.922 0 0 1 .18-1.084 7.496 7.496 0 0 1 
              3.126-1.788.928.928 0 0 1 1.028.384l.857 1.305a5.415 5.415 0 0 1 .376 0l.857-1.305a.928.928 0 0 1 1.027-.385c1.178.335 2.25.95 3.128 1.79a.923.923 0 0 1 .18
               1.084l-.713 1.39c.064.102.125.207.183.313l1.574.083c.401.02.75.297.85.691.15.59.226 1.191.226 1.796a7.34 7.34 0 0 1-.226 1.798.922.922 0 0 
               1-.847.69l-1.577.083c-.058.106-.119.21-.183.313l.713 1.392a.923.923 0 0 1-.181 1.083 7.5 7.5 0 0 1-3.126 1.788.928.928 0 0 1-1.028-.384l-.857-1.305a5.415 5.415
                0 0 1-.188.003Zm-1.926.503.943-1.437a.588.588 0 0 1 .546-.263 4.652 4.652 0 0 0 .874 0c.216-.02.427.08.546.263l.944 1.437a6.323 6.323 0 0 0 2.319-1.324l-.783-1.529a.587.587
                 0 0 1 .047-.612 4.32 4.32 0 0 0 .432-.741c.09-.2.285-.332.503-.343l1.734-.092c.096-.437.146-.879.146-1.323 0-.444-.05-.886-.146-1.322l-1.733-.092a.588.588 0 0 1-.504-.343
                 4.316 4.316 0 0 0-.432-.741.587.587 0 0 1-.047-.613l.783-1.528a6.325 6.325 0 0 0-2.32-1.324l-.943 1.437a.588.588 0 0 1-.546.262 4.642 4.642 0 0 0-.874 0 .588.588 
                 0 0 1-.546-.262l-.943-1.437a6.322 6.322 0 0 0-2.32 1.324l.783 1.528a.587.587 0 0 1-.047.613c-.17.235-.314.482-.431.74a.588.588 0 0 1-.504.344l-1.733.092a6.124 6.124
                 0 0 0-.146 1.322c0 .444.05.886.146 1.323l1.733.092a.588.588 0 0 1 .504.344c.117.258.261.505.431.74.13.179.148.416.047.612l-.783 1.529a6.324 6.324 
                 0 0 0 2.32 1.324Zm-.807-5.964a2.733 2.733 0 1 1 5.466 0 2.733 2.733 0 0 1-5.466 0Zm1.176 0a1.557 1.557 0 1 0 3.115 0 1.557 1.557 0 0 0-3.115 0Z" 
                 ></path></svg></a></div>
                </div>
    
                {% else %}
                <a class="nav-item nav-link" id="welcome" href="/">Welcome</a>
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
                <a class="nav-item nav-link" id="calculator" href="/public/calculator"
                >Calculator</a
                >
                <a class="nav-item nav-link" id="support" href="/public/support"
                >Support</a
                >
                <a class="nav-item nav-link" id="about" href="/public/about" aria-label="Settings">About</a>
                
                {% endif %} 
              </div>
            </div>
            
          </nav>
          
          
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
            messages %} {% for category, message in messages %} {% if category ==
              'error' %}
              <div class="alert alert-danger alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% else %}
              <div class="alert alert-success alter-dismissable fade show" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              {% endif %} {% endfor %} {% endif %} {% endwith %}
              
  <hr>
    <div background="gray" class="container bg-dark">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
      ></script>
      <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
      ></script>
      <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
      ></script>
      <style>
        #myChart {
          max-width: 400px;
          max-height: 400px;
        }
      </style>
      {% block javascript %}
      <script type="text/javascript">
      function deleteNote(noteId) {
        fetch("/delete-note", {
          method: "POST",
          body: JSON.stringify({ noteId: noteId }),
        }).then((_res) => {
          window.location.href = "/notes";
        });
      }
      </script>

      <script type="text/javascript">
      function openLedger(portfolioId) {
         fetch("/open-ledger", {
            method: "POST",
            body: JSON.stringify({ portfolioId: portfolioId }),
          }).then((_res) => {
            sessionStorage.setItem("PID",'3');
            window.location.href = "/ledger";
          
         });
        }
      </script>
      {% endblock %}
    
  </body>

  <footer style="text-align: center;">
    <div>
      <hr>
    </div>
    <!-- other footer content -->
    <div class="footer-links center-links">
        <a href="/public/about/">About Us</a>
        <a href="/public/support/">Contact Us</a>
    </div>
    <!-- Add your logo here -->
    <img src="{{ url_for('static', filename='images/Finance_logo.png') }}" alt="Your Logo" width="100" height="100">
    <p>&copy; 2023 Finance Application. All rights reserved.</p>
</footer>
</html>

website/templates/calculator.html
{% extends "base_auth.html" %} {% block title %}Calculator{% endblock %} {% block content
  %}
  <hr>

  <form class= "container   blue-card" method="POST">
    <h1>Loan Calculator</h1>
    <div class="form-group ">
      <label for="total">Loan Total</label>
      <input
        type="loan"
        class="form-control"
        id="loan"
        name="loan"
        placeholder="Enter loan amount"
      />
    </div>
    <div class="form-group">
      <label for="apr">APR</label>
      <input
        type="APR"
        class="form-control"
        id="APR"
        name="APR"
        placeholder="Enter APR"
      />
    </div>
    <div class="form-group">
      <label for="term">Term</label>
      <input
        type="term"
        class="form-control"
        id="term"
        name="term"
        placeholder="Enter term"
      />
    </div>

    <br />
    <button type="submit" class="btn btn-primary">Calculate</button>
    <hr>
    <div class= "container port-card">
      <h3>Monthly Payment: {{ monthly_payment }}</h3>
      <h3>Total Interest: {{ total_interest }}</h3>
      <h3>Total Cost: {{ total_cost }}</h3>
      
      
    </div>
  </form>
    
<hr>  
  {% endblock %}

website/templates/dashboard_admin.html
{% extends "base_auth.html" %} {% block title %}Admin Dashboard{% endblock %} {% block content 
  %}
      <h1 align="center">Admin Dashboard</h1>
      <br>
      <h3 align="center" style="color: aliceblue;">Enter User ID</h3>
  
  <form method="POST" action="{{ url_for('views.disable_user', target=target) }}">
    <textarea name="target" id="target" class="form-control"></textarea>
    <button type="submit" class="close.btn.btn-primary" aria-label="Disable">Disable</button>
  
    <button type="submit" class="close.btn.btn-primary" formaction="{{ url_for('views.enable_user', target=target) }}">Enable</button>
  </form>
      {% endblock %}

website/templates/info.html
{% extends "base_auth.html" %} {% block title %}Account Settings{% endblock %} {% block
    content %}
    <hr>
<div class = "container blue-card">
  <div class= "container col-md-4 col-md-offset-4 blue-card">
    <div class="container">
    <h1 align="center">Account Info!</h1>
    <ul class="list-group list-group-flush" id="user">
    </ul>
    <form method="POST">
      <form method="POST">
        <h3 align="center"> {{ user.username }}'s' Info</h3>
        <div class="form-group">
          <label for="username">Username: {{user.username}}</label>
       
        </div>
        <div class="form-group">
          <label for="email">Email Address: {{user.email}}</label>
          
        </div>
        <div class="form-group">
          <label for="email2">Backup Email Address: {{user.backup_email}}</label>
          
        </div>

        <br />

      </form>

      </div>

  </div>
  </div>

  <hr>
{% endblock %}
    

website/templates/login.html
{% extends "base_auth.html" %} {% block title %}Login{% endblock %} {% block
content %}
<hr>
{% if error %}
<div class="alert alert-danger" role="alert">
  {{ error }}
</div>
{% endif %}
<hr>
<div class= "container col-md-4 col-md-offset-4 blue-card">
  <div class="container mt-4">
    <h2>Login to Your Account</h2>
    <p>Welcome back! Please enter your credentials to access your financial dashboard.</p>




</div>
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
<hr>
<p class="mt-3">
  Don't have an account yet? <a href="{{ url_for('auth.sign_up') }}">Sign up here</a>.
</p>
<p>
  Forgot your password? <a href="{{ url_for('public.support') }}">Reset it here</a>.
</p>
</div>
<hr>
<p align="center">Don't have an account? <a href="/sign-up">Sign Up!</a></p>
{% endblock %}

website/templates/login_admin.html
{% extends "base_auth.html" %} {% block title %}Admin Login{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Admin Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}